### ISSUE TITLE
Leaked API Key

### ISSUE THREAD

**Issue by NihadBadalov** [itsEricWu/Emoji-Predictor#1]
hey Eric.
deleting the api key by just pushing a commit won't actually hide it -- it'll stay in the commit history. the commit in question is https://github.com/itsEricWu/Emoji-Predictor/commit/add2693cac6b624b34fc64331e3fc89a62d0f22b 

i recommend you to remove it; otherwise, bots and scrapers might scrape your api key and you'll get billed a lot of green presidents.

thanks

**Comment by itsEricWu** [comment]
Thank you! I will fix that.

**Comment by itsEricWu** [comment]
fixed
